[input]
recursive = true
entries = [ "./" ]

[output]
dir = "docs"

[languages]
[languages.appleScript]
singleline = "--"
[languages.as]
singleline = "//"
[languages.asp]
singleline = "'"
[languages.bat]
singleline = "@?rem"
[languages.btm]
singleline = "@?rem"
[languages.c]
singleline = "//+"
[languages.clj]
singleline = ";+"
[languages.cls]
singleline = "%"
[languages.cmake]
singleline =  "#"
[languages.cmd]
singleline = "@?rem"
[languages.coffee]
singleline =  "#"
[languages.cpp]
singleline = "//"
multiline_header = "/\\*+"
multiline_footer = "\\*+/"
multiline_margin = "\\*"
[languages.cs]
singleline = "//"
[languages.cson]
singleline =  "#"
[languages.d]
singleline = "//"
[languages.dtx]
singleline = "%"
[languages.erl]
singleline = "%"
[languages.frag]
singleline = "//"
[languages.glsl]
singleline = "//"
[languages.go]
singleline = "//"
[languages.groovy]
singleline = "//"
[languages.h]
singleline = "//"
[languages.hrl]
singleline = "%"
[languages.hs]
singleline = "--"
[languages.ini]
singleline = ";"
[languages.jade]
singleline = "//-"
[languages.js]
singleline = "//"
[languages.jsm]
singleline = "//"
[languages.jsx]
singleline = "//"
[languages.java]
singleline = "//+"
[languages.latex]
singleline = "%"
[languages.less]
singleline = "//"
[languages.lisp]
singleline = ";"
[languages.litcoffee]
singleline =  "#+"
literate = true
[languages.ls]
singleline =  "#+"
[languages.lua]
singleline = "--"
[languages.n]
singleline = "//"
[languages.m]
singleline = "//"
[languages.mel]
singleline = "//"
[languages.markdown]
singleline = ""
[languages.md]
singleline = ""
[languages.mm]
singleline = "//"
[languages.p]
singleline = "//"
[languages.pas]
singleline = "//"
[languages.php]
singleline = "//"
[languages.pl]
singleline =  "#+"
[languages.pm]
singleline =  "#"
[languages.pod]
singleline =  "#"
[languages.pp]
singleline = "//"
[languages.py]
singleline =  "#+"
[languages.rb]
singleline =  "#+"
[languages.rs]
singleline = "//[/!]?"
[languages.scala]
singleline = "//"
[languages.scpt]
singleline = "--"
[languages.scss]
singleline = "//"
[languages.sh]
singleline =  "#"
[languages.sql]
singleline = "--"
[languages.sty]
singleline = "%"
[languages.styl]
singleline = "//"
[languages.stylus]
singleline = "//"
[languages.swift]
singleline = "//"
[languages.t]
singleline =  "#"
[languages.tex]
singleline = "%"
[languages.ts]
singleline = "//"
[languages.v]
singleline = "//"
[languages.vala]
singleline = "//"
[languages.vapi]
singleline = "//"
[languages.vbe]
singleline = "'"
[languages.vbs]
singleline = "'"
[languages.vert]
singleline = "//"
[languages.vhdl]
singleline = "--"
[languages.vim]
singleline = "\""
[languages.r]
singleline =  "#"
[languages.toml]
singleline =  "#+"
[languages.wsc]
singleline = "'"
[languages.wsf]
singleline = "'"
[languages.yaml]
singleline =  "#"
