[package]
name = "rucco_lib"
version = "0.1.0"
authors = ["johan gall <johan.gall@gmail.com>"]

[dependencies]
syntect = "~1.0.1" # syntax highlighting
regex = "~0.1.77" # regexp to separate code from comments
hoedown = "~5.0.0" # markdown html rendering
